#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"

APP="$1"
IMAGE="$2"
HOSTNAME=$(hostname -f)

if [[ -f "$DOKKU_ROOT/$APP/SLACK_URL" || -f "$DOKKU_ROOT/SLACK_URL" ]]; then
    echo "-----> Notifying Slack ..."
    source $DOKKU_ROOT/$APP/ENV

    URL=$(dokku url $APP)
    TEXT="Deployed $APP to $HOSTNAME via $URL ${SLACK_TEXT:-}"
    SLACK_URL=$(cat "$DOKKU_ROOT/$APP/SLACK_URL" 2> /dev/null || cat "$DOKKU_ROOT/SLACK_URL" 2> /dev/null)
    SLACK_JSON="{ \
                  \"attachments\": [{ \
                  \"text\": \"$TEXT\", \
                  \"fallback\": \"$TEXT\", \
                  \"color\": \"good\", \
                  \"mrkdwn_in\": [\"text\"] \
                   }] \
                }"
    SLACK_RESULT=$(curl -s -d "payload=$SLACK_JSON" "${SLACK_URL}" -w "%{http_code}")
    echo "       ${SLACK_RESULT}"
fi
